import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";

import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { TopNav } from './_components/TopNav';


export const metadata = {
  title: "Create T3 Gallery",
  description: "Generated by PT",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col gap-4">
          <TopNav />
        <div className="w-full">
          {children}
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
