import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import "@uploadthing/react/styles.css";

import { ClerkProvider } from '@clerk/nextjs'
import { TopNav } from './_components/TopNav';
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";


export const metadata = {
  title: "Create T3 Gallery",
  description: "Generated by PT",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
    <NextSSRPlugin
          /**
           * UploadThing needs to get info from your server to get permissions info. 
           * Normally this means a loading state. 
           * We built an optional plugin to prevent that
           * 
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
      <body className="flex flex-col gap-4">
          <TopNav />
        <div className="w-full">
          {children}
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
